export const sampleStringOfClaudesResponse = `I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.
I want another slice.`;